/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq.tables.records

import neuralplayer.server.model.jooq.tables.PlaylistTrack
import org.jooq.Field
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl

import javax.annotation.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
@SuppressWarnings( "unchecked")
class PlaylistTrackRecord : UpdatableRecordImpl<PlaylistTrackRecord>, Record2<Long, Long> {

	/**
	 * Getter for `neural_player.playlist_track.playlist_id`.
	 */
	/**
	 * Setter for `neural_player.playlist_track.playlist_id`.
	 */
	var playlistId: Long
		get() = get(0) as Long
		set(value) = set(0, value)

	/**
	 * Getter for `neural_player.playlist_track.track_id`.
	 */
	/**
	 * Setter for `neural_player.playlist_track.track_id`.
	 */
	var trackId: Long
		get() = get(1) as Long
		set(value) = set(1, value)

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	override fun key(): Record2<Long, Long> {
		return super.key() as Record2<Long, Long>
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	override fun fieldsRow(): Row2<Long, Long> {
		return super.fieldsRow() as Row2<Long, Long>
	}

	/**
	 * {@inheritDoc}
	 */
	override fun valuesRow(): Row2<Long, Long> {
		return super.valuesRow() as Row2<Long, Long>
	}

	/**
	 * {@inheritDoc}
	 */
	override fun field1(): Field<Long> {
		return PlaylistTrack.PLAYLIST_TRACK.PLAYLIST_ID
	}

	/**
	 * {@inheritDoc}
	 */
	override fun field2(): Field<Long> {
		return PlaylistTrack.PLAYLIST_TRACK.TRACK_ID
	}

	/**
	 * {@inheritDoc}
	 */
	override fun component1(): Long {
		return playlistId
	}

	/**
	 * {@inheritDoc}
	 */
	override fun component2(): Long {
		return trackId
	}

	/**
	 * {@inheritDoc}
	 */
	override fun value1(): Long {
		return playlistId
	}

	/**
	 * {@inheritDoc}
	 */
	override fun value2(): Long {
		return trackId
	}

	/**
	 * {@inheritDoc}
	 */
	override fun value1(value: Long): PlaylistTrackRecord {
		playlistId = value
		return this
	}

	/**
	 * {@inheritDoc}
	 */
	override fun value2(value: Long): PlaylistTrackRecord {
		trackId = value
		return this
	}

	/**
	 * {@inheritDoc}
	 */
	override fun values(value1: Long, value2: Long): PlaylistTrackRecord {
		value1(value1)
		value2(value2)
		return this
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaylistTrackRecord
	 */
	constructor() : super(PlaylistTrack.PLAYLIST_TRACK)

	/**
	 * Create a detached, initialised PlaylistTrackRecord
	 */
	constructor(playlistId: Long, trackId: Long) : super(PlaylistTrack.PLAYLIST_TRACK) {

		set(0, playlistId)
		set(1, trackId)
	}

	companion object {

		private val serialVersionUID: Long = 683818039
	}
}
