/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq

import neuralplayer.server.model.jooq.tables.*
import org.jooq.Index
import org.jooq.OrderField
import org.jooq.impl.Internal

import javax.annotation.Generated

/**
 * A class modelling indexes of tables of the `neural_player` schema.
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
object Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	val PLAYLIST_PLAYLIST_CREATOR_ID_FK = Indexes0.PLAYLIST_PLAYLIST_CREATOR_ID_FK
	val PLAYLIST_PRIMARY = Indexes0.PLAYLIST_PRIMARY
	val PLAYLIST_TRACK_PLAYLIST_TRACK_TRACK_ID_FK = Indexes0.PLAYLIST_TRACK_PLAYLIST_TRACK_TRACK_ID_FK
	val PLAYLIST_TRACK_PRIMARY = Indexes0.PLAYLIST_TRACK_PRIMARY
	val TRACK_PRIMARY = Indexes0.TRACK_PRIMARY
	val USER_PRIMARY = Indexes0.USER_PRIMARY
	val USER_USER_EMAIL_UNIQUE = Indexes0.USER_USER_EMAIL_UNIQUE
	val USER_USER_NAME_UNIQUE = Indexes0.USER_USER_NAME_UNIQUE
	val USER_TRACK_PRIMARY = Indexes0.USER_TRACK_PRIMARY
	val USER_TRACK_USER_TRACK_TRACK_ID_FK = Indexes0.USER_TRACK_USER_TRACK_TRACK_ID_FK

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private object Indexes0 {
		var PLAYLIST_PLAYLIST_CREATOR_ID_FK = Internal.createIndex("playlist_creator_id_fk", Playlist.PLAYLIST, arrayOf(Playlist.PLAYLIST.CREATOR_ID), false)
		var PLAYLIST_PRIMARY = Internal.createIndex("PRIMARY", Playlist.PLAYLIST, arrayOf(Playlist.PLAYLIST.ID), true)
		var PLAYLIST_TRACK_PLAYLIST_TRACK_TRACK_ID_FK = Internal.createIndex("playlist_track_track_id_fk", PlaylistTrack.PLAYLIST_TRACK, arrayOf(PlaylistTrack.PLAYLIST_TRACK.TRACK_ID), false)
		var PLAYLIST_TRACK_PRIMARY = Internal.createIndex("PRIMARY", PlaylistTrack.PLAYLIST_TRACK, arrayOf(PlaylistTrack.PLAYLIST_TRACK.PLAYLIST_ID, PlaylistTrack.PLAYLIST_TRACK.TRACK_ID), true)
		var TRACK_PRIMARY = Internal.createIndex("PRIMARY", Track.TRACK, arrayOf(Track.TRACK.ID), true)
		var USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, arrayOf(User.USER.ID), true)
		var USER_USER_EMAIL_UNIQUE = Internal.createIndex("user_email_unique", User.USER, arrayOf(User.USER.EMAIL), true)
		var USER_USER_NAME_UNIQUE = Internal.createIndex("user_name_unique", User.USER, arrayOf(User.USER.USERNAME), true)
		var USER_TRACK_PRIMARY = Internal.createIndex("PRIMARY", UserTrack.USER_TRACK, arrayOf(UserTrack.USER_TRACK.USER_ID, UserTrack.USER_TRACK.TRACK_ID), true)
		var USER_TRACK_USER_TRACK_TRACK_ID_FK = Internal.createIndex("user_track_track_id_fk", UserTrack.USER_TRACK, arrayOf(UserTrack.USER_TRACK.TRACK_ID), false)
	}
}
