/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq

import neuralplayer.server.model.jooq.tables.*

import javax.annotation.Generated

/**
 * Convenience access to all tables in neural_player
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
object Tables {

	/**
	 * The table `neural_player.playlist`.
	 */
	val PLAYLIST = Playlist.PLAYLIST

	/**
	 * The table `neural_player.playlist_track`.
	 */
	val PLAYLIST_TRACK = PlaylistTrack.PLAYLIST_TRACK

	/**
	 * The table `neural_player.track`.
	 */
	val TRACK = Track.TRACK

	/**
	 * The table `neural_player.user`.
	 */
	val USER = User.USER

	/**
	 * The table `neural_player.user_track`.
	 */
	val USER_TRACK = UserTrack.USER_TRACK
}
