/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq.tables

import neuralplayer.server.model.jooq.Indexes
import neuralplayer.server.model.jooq.Keys
import neuralplayer.server.model.jooq.NeuralPlayer
import neuralplayer.server.model.jooq.tables.records.UserTrackRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.TableImpl

import javax.annotation.Generated
import java.util.Arrays

/**
 * This class is generated by jOOQ.
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
class UserTrack : TableImpl<UserTrackRecord> {

	/**
	 * The column `neural_player.user_track.user_id`.
	 */
	val USER_ID: TableField<UserTrackRecord, Long> = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "")

	/**
	 * The column `neural_player.user_track.track_id`.
	 */
	val TRACK_ID: TableField<UserTrackRecord, Long> = createField("track_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "")

	/**
	 * The column `neural_player.user_track.preference_score`.
	 */
	val PREFERENCE_SCORE: TableField<UserTrackRecord, Double> = createField("preference_score", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "")

	/**
	 * The class holding records for this type
	 */
	override fun getRecordType(): Class<UserTrackRecord> {
		return UserTrackRecord::class.java
	}

	/**
	 * Create an aliased `neural_player.user_track` table reference
	 */
	constructor(alias: String = "user_track")
			: this(DSL.name(alias), USER_TRACK)

	/**
	 * Create an aliased `neural_player.user_track` table reference
	 */
	constructor(alias: Name)
			: this(alias, USER_TRACK)

	private constructor(alias: Name, aliased: Table<UserTrackRecord>?, parameters: Array<Field<*>>? = null)
			: super(alias, null, aliased, parameters, DSL.comment(""))

	constructor(child: Table<*>, key: ForeignKey<*, UserTrackRecord>)
			: super(child, key, USER_TRACK)

	/**
	 * {@inheritDoc}
	 */
	override fun getSchema(): Schema {
		return NeuralPlayer.NEURAL_PLAYER
	}

	/**
	 * {@inheritDoc}
	 */
	override fun getIndexes(): List<Index> {
		return Arrays.asList(Indexes.USER_TRACK_PRIMARY,
				Indexes.USER_TRACK_USER_TRACK_TRACK_ID_FK)
	}

	/**
	 * {@inheritDoc}
	 */
	override fun getPrimaryKey(): UniqueKey<UserTrackRecord> {
		return Keys.KEY_USER_TRACK_PRIMARY
	}

	/**
	 * {@inheritDoc}
	 */
	override fun getKeys(): List<UniqueKey<UserTrackRecord>> {
		return Arrays.asList(Keys.KEY_USER_TRACK_PRIMARY)
	}

	/**
	 * {@inheritDoc}
	 */
	override fun getReferences(): List<ForeignKey<UserTrackRecord, *>> {
		return Arrays.asList(Keys.USER_TRACK_USER_ID_FK,
				Keys.USER_TRACK_TRACK_ID_FK)
	}

	fun user(): User {
		return User(this, Keys.USER_TRACK_USER_ID_FK)
	}

	fun track(): Track {
		return Track(this, Keys.USER_TRACK_TRACK_ID_FK)
	}

	/**
	 * {@inheritDoc}
	 */
	override fun `as`(alias: String): UserTrack {
		return UserTrack(DSL.name(alias), this)
	}

	/**
	 * {@inheritDoc}
	 */
	override fun `as`(alias: Name): UserTrack {
		return UserTrack(alias, this)
	}

	/**
	 * Rename this table
	 */
	override fun rename(name: String): UserTrack {
		return UserTrack(DSL.name(name), null)
	}

	/**
	 * Rename this table
	 */
	override fun rename(name: Name): UserTrack {
		return UserTrack(name, null)
	}

	companion object {

		private const val serialVersionUID: Long = -1418451932

		/**
		 * The reference instance of `neural_player.user_track`
		 */
		val USER_TRACK = UserTrack()
	}
}
