/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq.tables.pojos

import javax.annotation.Generated
import java.io.Serializable
import java.sql.Timestamp

/**
 * This class is generated by jOOQ.
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
data class Track(var id: Long,
				 var title: String,
				 var artist: String?,
				 var album: String?,
				 var file: ByteArray,
				 var fileExtension: String,
				 var createdAt: Timestamp) : Serializable {

	companion object {

		private const val serialVersionUID: Long = 147378989
	}
}
