/*
 * This file is generated by jOOQ.
 */
package neuralplayer.server.model.jooq.tables.pojos

import javax.annotation.Generated
import java.io.Serializable
import java.sql.Timestamp

/**
 * This class is generated by jOOQ.
 */
@Generated(value = ["http://www.jooq.org", "jOOQ version:3.11.2"], comments = "This class is generated by jOOQ")
data class User(var id: Long,
				var username: String,
				var email: String,
				var password: String,
				var displayName: String,
				var roles: String,
				var createdAt: Timestamp) : Serializable {

	companion object {
		private const val serialVersionUID: Long = -624230706
	}
}
